### ISSUE TITLE
Support for 10x Genomics data? 

### ISSUE THREAD

**Issue by topherconley** [churchill-lab/emase-zero#2]
Hi,
I have a client interested interested in single cell ASE based on the 10x Genomics platform. The default Cell Ranger pipeline (using STAR 2.5) is not capable of resolving ambiguously mapped reads across a diploid genome and she is in need of another option.  Any suggestions? 
Thanks in advance, 
Chris

**Comment by kbchoi-jax** [comment]
We have been extending the emase pipeline to 10X scRNA-Seq data but have not released it yet. We are open for collaboration though. Could you give us a bit more detailed information about your project? If privacy matters, please email me at [kb.choi@jax.org](mailto:kb.choi@jax.org). Thanks!

**Comment by topherconley** [comment]
Very cool. At present, the client has very poor-quality pilot data from 10x at this point, but I'll loop them into the conversation to see what their interest level is on collaboration. Expect an email shortly.
