### ISSUE TITLE
Enquiring about presence of maternal and paternal allele in the transcript-lengths file

### ISSUE THREAD

**Issue by rituparna-13** [churchill-lab/emase-zero#4]
In the GitHub page http://churchill-lab.github.io/emase-zero/ you mentioned using **transcript-lengths** file which contained information about the transcripts being maternal or paternal (e.g. ENSMUST00000000001_M (maternal) and ENSMUST00000000001_P (paternal)). 
Can you please describe how did you identify the transcripts with maternal and paternal allele? 
Did you use any particular method to identify them?

**Comment by MikeWLloyd** [comment]
@rituparna-13 this is an old issue, and I am not sure if you solved your problem. 

I believe that they used `prepare-emase` from the original emase package. 

Please see the documentation here: https://emase.readthedocs.io/en/latest/usage.html
